name: bet_minder
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  url_launcher: ^6.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  scrollable_positioned_list: ^0.3.8
  auto_size_text: ^3.0.0
  dart_style: ^2.3.4
  html: ^0.15.4
  flutter_keyboard_visibility: ^6.0.0
  uuid: ^4.3.3
  fl_chart: ^0.67.0
  apphud: 2.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/reading/
    - assets/images/events/
    - assets/icons/
    - assets/fonts/


  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProText-Bold.ttf
          weight: 600
        - asset: assets/fonts/SFProText-Semibold.ttf
          weight: 700
